title: Cadmus
description: Cadmus technical documentation
theme: just-the-docs

url: https://vedph.github.io/cadmus-doc

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

mermaid:
  version: "11.4.1"

toc:
  - title: "Home"
    url: /
  - title: "Models"
    url: /models/index
    children:
      - title: "Shared Models"
        url: /models/shared
      - title: "Thesauri"
        url: /models/thesauri
  - title: "Frontend"
    url: /frontend/index
  - title: "Data Migration"
    url: /migration/index
    children:
      - title: "Graphs"
        url: /migration/graph/index
