title: Cadmus
description: Cadmus technical documentation
theme: just-the-docs

url: https://vedph.github.io/cadmus-doc

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
